// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

#nullable disable

namespace April2024B.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250429161018_v3")]
    partial class v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Maratonac", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrojNagrada")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JMBG")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SrednjaBrzina")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Maratonci");
                });

            modelBuilder.Entity("Models.Trka", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrojTakmicara")
                        .HasColumnType("int");

                    b.Property<double>("DuzinaStaze")
                        .HasColumnType("float");

                    b.Property<string>("Lokacija")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PocetakTrke")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("TrajanjeTrke")
                        .HasColumnType("time");

                    b.HasKey("ID");

                    b.ToTable("Trke");
                });

            modelBuilder.Entity("Models.Ucesce", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("MaratonacID")
                        .HasColumnType("int");

                    b.Property<int>("StartniBroj")
                        .HasColumnType("int");

                    b.Property<int>("TrenutnaPozicija")
                        .HasColumnType("int");

                    b.Property<int?>("TrkaID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("VremeIstrcano")
                        .HasColumnType("time");

                    b.HasKey("ID");

                    b.HasIndex("MaratonacID");

                    b.HasIndex("TrkaID");

                    b.ToTable("Ucesca");
                });

            modelBuilder.Entity("Models.Ucesce", b =>
                {
                    b.HasOne("Models.Maratonac", "Maratonac")
                        .WithMany("UcescaM")
                        .HasForeignKey("MaratonacID");

                    b.HasOne("Models.Trka", "Trka")
                        .WithMany("UcescaT")
                        .HasForeignKey("TrkaID");

                    b.Navigation("Maratonac");

                    b.Navigation("Trka");
                });

            modelBuilder.Entity("Models.Maratonac", b =>
                {
                    b.Navigation("UcescaM");
                });

            modelBuilder.Entity("Models.Trka", b =>
                {
                    b.Navigation("UcescaT");
                });
#pragma warning restore 612, 618
        }
    }
}
